# Install Golang
- name: Set Go Version
  set_fact: 
    go_version: "1.11"
  tags: golang

- name: Download Go 
  get_url:
    url: https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz
    dest: ~/Downloads/go.linux-amd64.tar.gz
  tags: golang

- name: Remove old Go installation
  file:
    path: /usr/local/go
    state: absent
  tags: golang

- name: extract Go 
  unarchive:
    src: ~/Downloads/go.linux-amd64.tar.gz
    dest: /usr/local
    copy: no
  tags: golang

- name: Remove Go Download
  file:
    path: ~/Downloads/go.linux-amd64.tar.gz
    state: absent
  tags: golang

- name: Add GOPATH to shells
  lineinfile:
    path: "{{ item }}"
    line: "export GOPATH=~/go"
  loop:
    - "~/.bashrc"
    - "~/.zshrc"
  tags: golang
  
- name: Add /usr/local/go/bin to PATH of different shells
  lineinfile:
    path: "{{ item }}"
    line: "export PATH=$PATH:/usr/local/go/bin"
  loop:
    - "~/.bashrc"
    - "~/.zshrc"
  tags: golang



