# Install several packages
- name: Add repositories
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - ppa:webupd8team/java
  tags: apt

- name: Only run "update_cache=yes" if the last one is more than 7 days (604800s) ago
  apt:
    update_cache: yes
    cache_valid_time: 604800
  tags: apt

- name: Install packages with apt
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - git
    - terminator
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - htop
    - vlc
    - wireshark
    - default-jdk
    - nodejs
    - npm
  tags: apt
