# Install Google Cloud SDK
- name: Add Google Cloud GPG key
  shell: "curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -"
  tags: gc

- name: "apt | ensure Google Cloud repo present"
  apt_repository:
    repo: "deb http://packages.cloud.google.com/apt cloud-sdk-{{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  tags: gc

- name: Install Google Cloud SDK with apt
  apt: 
    name: "google-cloud-sdk"
    state: present
    update_cache: yes
  tags: gc
