# Install virtualbox
- name: Configure the Oracle APT key
  apt_key: 
    url: "{{ item }}"
    state: present
  with_items:
    - "https://www.virtualbox.org/download/oracle_vbox.asc"
    - "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
  tags: virtualbox

# - name: Add Oracle key
#   shell: "wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -"
#   tags: virtualbox

- name: "apt | ensure Virtualbox repo present"
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present
    update_cache: yes
  tags: virtualbox

- name: "apt | Install Virtualbox 5.2"
  apt:
    name: virtualbox-5.2
    state: present
    update_cache: yes
  tags: virtualbox
